Instructors' Resources for Teaching Statistical Modeling
========================================================

NOTE: This document is being constructed over the course of the Fall 2012 semester.  Check back for updates!

### Day-by-Day Syllabus for Statistical Modeling

* **CURRENT SEMESTER** Fall 2012: [Math 155 at Macalester College](Fall2012/Schedule.html) including instructor notes.
* Past Semesters
    * [Spring 2011](http://test.causeweb.org/wiki/mosaic/index.php/Math_155_Kaplan_Spring_2011_Day-by-Day) on the MOSAIC wiki.

### Exercises
``` {r echo=FALSE}
acroChapter <- function(chap,access="ISMf12",probnum=NULL,label=chap){
  if (!is.null(probnum)) probnum <- paste("#",probnum,sep="")
  
  paste("<a href='",
              paste("https://dl.dropbox.com/u/5098197/Exercises/HTML/",
                    "SM2-Chapter-",chap,"-Problems/SM2-Chapter-",chap,
                    "-Problems-A.html?access=",access,probnum,sep=""),
              "'>",label,"</a>",sep="")
}
```

* [PDF format](http://www.mosaic-web.org/Repository/DannyKaplan/Exercise-Collection.pdf) (for all chapters)
* HTML Format (individual chapters): `r I(acroChapter(chap=1))`, `r I(acroChapter(chap=2))`, `r I(acroChapter(chap=3))`, `r I(acroChapter(chap=4))`, `r I(acroChapter(chap=5))`, `r I(acroChapter(chap=6))`, `r I(acroChapter(chap=7))`, `r I(acroChapter(chap=8))`, `r I(acroChapter(chap=9))`, `r I(acroChapter(chap=10))`, `r I(acroChapter(chap=11))`, `r I(acroChapter(chap=12))`, `r I(acroChapter(chap=13))`, `r I(acroChapter(chap=14))`, `r I(acroChapter(chap=15))`, `r I(acroChapter(chap=16))`, `r I(acroChapter(chap=17))`, `r I(acroChapter(chap=18))`

Answer Keys are available in either PDF or HTML format to instructors, with verification of instructor status.  Contact <mailto:kaplan@macalester.edu>.   

### Blogs

Published
* [Instructor update on the mosaic package](Blog/Teaching-with-mosaic.html)
* [List of `mosaic` related changes in the corrected (Summer 2012) printing](Errata/errata.html).  This is useful for students who have the first printing of the second edition, e.g. students with used books in Fall 2012.  There are just a handful of changes, but it's important to be aware of them.
* [An orientation for parents](http://rpubs.com/dtkaplan/1279)
* [Adding your own data sets and software using `fetchData`](Blog/DataThroughFetchData.html)
* [Reading Google Spreadsheets into R](Blog/GoogleSpreadsheets.html) Instructions are given both for downloading a CSV version and, if you can install `RCurl` on your system, using `fetchGoogle()`.

Upcoming
* Groupwise models and `mm`
* Simulations
* Teaching markdown/knitr


### Activities

#### Introductory

##### Patterns in Randomness

Math 155 spends most of the first half of the course setting students up to construct models.  Statistical inference, with its connections to randomness, is added in the second half.  On the very first day, however, I do an activity or two involving randomness to foreshadow statistical inference.  (There is also a discussion of confidence intervals in Chapter 5 of the 2nd edition, in the middle of the first half of the course.)

* [Magic Coins](Notes/magic-coins.html) --- an activity to help students see that they must be able to characterize randomness in order to draw reasonable conclusions.
* [Statistical Fingerprints](Notes/coin-flipping.html) --- statistics provides techniques to detect relationships.  As a demonstration of this, consider detecting whether there is a human making up coin flips or a genuine, physical coin-flipping process. 

##### Computing

Even on the first day, I have students log in to the [RStudio](http:/www.rstudio.com) server and do a few guided calculations.  On the second day I introduce them more systematically to the syntax and data organization.

* [Data Organization](Activities/IntroOrganizingData.html)

##### Data Organization

* [The Elevator Experiment](https://dl.dropbox.com/u/5098197/Exercises/HTML/SM2-Chapter-3-Problems/SM2-Chapter-3-Problems-A.html?access=ISMf12#336) --- see notes from [2012-09-10](Notes/2012-09-10.html) for the sorts of errors to point out in the spreadsheets.
* [How Many Variables?](Activities/HowManyVariables.html) Distinguishing between summary tables and basic case-variable data tables. [PDF handout](https://dl.dropbox.com/u/5098197/ISM/How-Many-Variables.pdf)

##### Sampling and Bias

* [Selecting Library Books](Activities/SelectingLibraryBooks.html)

#### Modeling

* "Unfit" models. Rather than starting students with fitted models, I have them construct models with parameters that they pull out of their heads, and then evaluate these models against data.  My intention is to help the students understand the criterion for picking parameters, which is otherwise hidden behind the software such as `lm()`. [Notes](Notes/2012-09-17.html) and [handout](https://dl.dropbox.com/u/5098197/ISM/Unfit-Models.pdf)

#### Language of Models

Some classroom notes on the [language of models](Notes/2012-09-21.html).  There's also an in-class activity based on a program `mLM()`.

*[Rough notes on the in-class activity](http://dl.dropbox.com/u/5098197/Exercises/HTML/ISM-Selecting-Model-Terms/ISM-Selecting-Model-Terms-A.html?access=ISM3)  These need to be updated to reflect that the program is called `mLM()` and is loaded with `fetchData("mLM.R")`.

A few students will have to be reminded of the meaning of "slope" and "intercept," but the majority will think this is obvious.  More students will have trouble with interpreting the coefficients on levels of a categorical variable as a "difference," akin to a slope.  

The biggest cognitive challenge is for students to understand that the "shape" of a model is set by the choice of terms in the model.  It's worth emphasizing that, despite the obvious differences between the pattern of men's and women's swimming records over the years, the model won't reflect this unless an interaction term is included.

The activity using the `mLM()` program may be helpful.  Note in particular that there is a slot to choose the dependent variable on the graph.  It's well worth going over why the graph of model values is different depending on the choice of the variable for the axis.  Also, many students won't understand why a "straight line" model like "time ~ year" doesn't show up as a straight line when the model values are plotted against "sex".

This lesson is really about the difference between a variable and a "model term".  Later on, we'll deal with the meaning of coefficients.  Before we can do that, we have to introduce "model vectors" and explain how a categorical variable gets translated into a set of model vectors.

#### Untangling
* An introduction using house prices.  This is based on a problem involving house prices in Saratoga Springs, NY developed by [Prof. Richard De Veaux](http://sites.williams.edu/rdeveaux/) of Williams College.  [Instructor Notes](Activities/UntanglingHousesInstructorNotes.html], [Student handout](Activities/UntanglingHousePrices.pdf), in which students construct a multiple-regression model of house price as a function of various features of the house.  