```{r echo=FALSE,results="hide"}
moodle <- function(item,name){
  paste("\n* What is the most important thing you learned from this reading?\n* If there was anything you found confusing, please describe it.\n\n    <a name='",name,"'/a><a href='https://moodle.macalester.edu/mod/assign/view.php?id=",item,"'>Moodle link</a>\n\n<hr>", sep="")
}
```

## Short Essays and Reading Reflections for Epidemiology

A "reading reflection" is a short essay --- one or two paragraphs that you should be able to write in about five minutes.  

-----------


### Epidemiology as a Liberal Art: Reading Reflection

* Fraser describes five "kinds of thinking."  Were you surprised at what they are?  Are they really about the liberal arts?
`r I(moodle(13654,"fraser"))`

### The Score: Reading Reflection

* What was the system for evaluating the condition of a new-born that the APGAR score replaced? 
`r I(moodle(13652,"apgar"))`

### Your Own APGAR score: <a name="apgarscore">Short Essay</a>

One of the themes in Atul Gawande’s essay, “[The Score](http://www.newyorker.com/archive/2006/10/09/061009fa_fact?currentPage=1),” in *Better: A Surgeon’s Notes on Performance*, is the emergence of the APGAR score as a way to measure birth outcomes. Following the suggestion of former CDC head David Fraser in his [New England Journal of Medicine](http://dl.dropbox.com/u/5098197/Epidemiology/Fraser-NEJM-epidemiology.pdf) article that “analogic thinking” is an important aspect of epidemiology that can contribute to a liberal education, your assigned task is to invent an APGAR score of your own in an area of your own choosing. Some suggestions:

* An APGAR score for academic advising at college. (DTK has proposed this at Macalester.) 
* An APGAR score for sports performance. 
* An APGAR score for whether you have done your work for the next school day. 
* An APGAR score for feedback to professors about class sessions. (Quantify the one-minute essays!)

Be creative! But also be specific about what components would go into the overall score, paying particular attention to the importance of being able to score the components at a glance.

Your answer should consist of a brief description of the problem, followed by a list of the components in your score. Each of these components should have a one- or two-sentence explanation that would make sense to someone familiar with the area of application. For example, in my academic advising score, one of the components is whether the student has decided on a major. [Hand in on Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=15122)

---------------

### Your Own <a name="glossary">Glossary of Epidemiology</a>

As you read in Epi, you will come across many terms that are either new to you or would be new to someone you are telling about epidemiology.  Keep track of these in a Google Doc as the semester goes by.

**Create the Google Doc now**. Share it with `kaplan@macalester.edu`.  Then go to [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=15123) and enter the link to that document.  You might also want to bookmark it in your browser, so you can easily get back to it.

Over the semester, add to the glossary.  When you don't know the meaning of a term, and the definition doesn't make sense to you, just write down the term and come back to it later.  You'll learn more if you write the definition in your own words.

----------------

### Welcome to the <a name="theIsland">Island.</a>

One of the goals of this course is to give you insight into how epidemiological data is collected and how epidemiological studies are performed. A great way to do this is for you to perform actual studies on actual populations. But this is impractical in the scope of a one-semester introductory course, to say nothing about the practical difficulties of setting up studies and the ethical difficulties relating to privacy and contact with patients by non-professionals.

Computers to the rescue. Prof. Michael Bulmer, a statistician at the University of Queensland in Brisbane, Australia, has been developing a realistic population simulator: [The Island](http://island.maths.uq.edu.au/). (Prof. Bulmer spent his sabbatical in Spring/Summer 2010 at Macalester, which was the first site outside Australia to use the simulation.) We'll use this as the substrate for your studies. Of course this means that your results won't be applicable to actual human populations, but on the other hand you'll be able to get much more data in a much shorter time, and even to impose interventions on the people of The Island that would be impractical and unethical on real humans.

Each student has his or her own account, effectively working on his or her own copy of the population on The Island. (When working on a group, you may want to all use the same account.) 

Accounts were created for most students based on the enrollment information available at the beginning of the semester. To get your password, follow [this link](http://island.maths.uq.edu.au/password.php) and enter your Macalester email address. Your island password will be mailed to you. If your email is not recognized as a valid account ID, contact Prof. Kaplan who will arrange to have an account set up for you.

Once you have set up your account and received your password, you [login here](http://island.maths.uq.edu.au/access.php?/index.php).

-------------

### Truth and Death in Iraq Under Sanctions: Reading Reflection

* Of course, you have no direct way to evaluate the claims made in this article.  What do you look for when assessing the reliability or truthfulness of the claims?
`r I(moodle(15121,"iraq"))`


### Planning for <a name="project1a">Group Project 1</a>

Your group should make a preliminary pan for the collection of data.
    * How you will sample.
    * What data you will record.
    * How you will organize your data.

In class, we'll talk about what's needed to do the necessary calculations.  Then you can revise your plans accordingly. 

Record your plan in a Google document that's shared with the entire group.  *Each member of the group* should paste in a link to the document on Moodle, [here](https://moodle.macalester.edu/mod/assign/view.php?id=15224).


-------------

### The Cancer Cluster Myth: Reading Reflection

* What is it about cancer that lends itself to the dubious detection an "outbreak," whereas for other causes of illness (e.g., food contamination) there doesn't seem to be such a problem?
`r I(moodle(15226,"clustermyth"))`

### *Better*, "On Washing Hands": Reading Reflection

* Give an example from the reading of "positive deviance."  Give an example of how the concept might apply at Macalester or in some other domain of importance to you?
* Why was Semmelweis ineffective?
`r I(moodle(22645, "washinghands"))`

### Koch's Postulates: Reading Reflection

In this reading reflection, consider the ways in which Koch's postulates make sense or not.  As a point of reference, here is a recent article on [the ecosystem in the gut](http://www.nytimes.com/2011/11/01/health/scientist-examines-possible-link-between-antibiotics-and-obesity.html).  
* Do antibiotics have consequences that go beyond the "bad-guy" bacterium?
* How are Koch's postulates "reductionist"?
`r I(moodle(15240,"koch"))`

### Survival Analysis: Reading Reflection

This is a somewhat technical article and it is likely that you will find it difficult or impossible to understand in its entirety.  That is a situation that you will find often in your career.
* What is your strategy for reading something that is only partially comprehensible to you?
* You are fortunate to have access to an expert in survival analysis, Prof. Victor Addona.  Formulate a question that will help you to understand this reading.  (Then ask it in class!)
* What is "censoring" in the context of survival analysis?
`r I(moodle(15252,"survival"))`

### Essential Epidemiology Ch. 11: Reading Reflection

* What is the point of a forest plot?
* What is meta-analysis?
`r I(moodle(15265, "EE11"))`

### <a name="insurance">Health Insurance: Your View</a>

This short essay is intended to probe what you already know about health insurance, before we read about it. A few paragraphs will do nicely.
First, give a one- or two-sentence definition of "insurance," a general category that includes life insurance, unemployment insurance, disability insurance, car insurance, home insurance.  **Don't look in the dictionary** --- give your own definition based on your current knowledge.

Second, describe your understanding of how health insurance currently works. Some aspects that you should consider:

* How does one acquire or sign up for health insurance?
* How much does it cost?
* What does it cover?  What health-related items doesn't it cover?

Third, say something about how you think health insurance should work:

* What should be covered?  What should be left out?
* Should everyone pay the same amount? If not, how is it determined how much an individual’s health insurance premiums should be? If so, how should it be determined what the payment amount is?
* Who pays for the balance (if any) of the cost of the health care that's actually delivered?
* Should people be required to have health insurance? Should it be provided for free?

[Hand in on Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=15869).

------------------
### <a name="fatalmistake">A Possibly Fatal Mistake</a>

* Look through the chronology in the article.  If Mr. Androes had had health insurance would the outcome of have been different?
* How does the article square with what we've been reading about PSA testing?

`r I(moodle(15264, "fatal"))`

------------------

### Reading Reflection on Gigerenzer *et al.* I and II

* What do the authors mean by saying, "patients seek certainty when there is none"?
* What's wrong with lifetime risk measures?
`r I(moodle(15264, "giger12"))`

### <a name="rhetoric">Rhetoric of Screening</a>

Here is an [editorial from the Minneapolis Star Tribune](http://dl.dropbox.com/u/5098197/Epidemiology/breast-cancer-screening.pdf) on Aug 11, 2009.
Write a couple of paragraphs in the form of a letter to the editor taking on this editorial from an informed epidemiological perspective. Your letter might be supportive or critical of the editorial, but your point of view should be professional.

As you pull together your thoughts in preparation for writing the letter, you might start by summarizing and explaining the arguments made in the editorial that the advantages of screening exceed the disadvantages. Are there any arguments that are rhetorical, mere turns of phrasing rather than careful reasoning?

[Hand in on Moodle.](https://moodle.macalester.edu/mod/assign/view.php?id=15396)

--------------------

### A Deadly Misdiagnosis: Reading Reflection

* This article expresses a theory that better diagnostic tests would dramatically improve the situation.  What evidence --- either empirical or theoretical --- is given in support of this theory?
`r I(moodle(15811 ,"misdiagnosis"))

### The Great Influenza

#### Pages 1-47: Reading Reflection

* Many medical treatments in the past strike us today as silly.  But they often made sense at the time, emerging logically from a theoretical framework.  Pick an example from the reading and explain briefly how the treatment made sense in terms of the theory.
`r I(moodle(15120,"GI1"))`

#### Pages 89-116: Reading Reflection

* Influenza is the leading cause of death from infectious disease in the US.  What aspects of the influenza virus, the human immune system, and the interaction of the two contribute to this?
`r I(moodle( 21684 , "GI3"))`
