Math 155: Introduction to Statistical Modeling
====================

``` {r echo=FALSE}
# Setting up the calendar material
makeDayLinkName <- function(month,day,year=2012){
  paste("Day-", year, "-", month, "-", day, sep="")
}
dd <- function(month,day,year=2012) {
  paste("<a target='self' href='#",makeDayLinkName(month,day,year),"'>",day,"</a>",sep="")
}
classDayContents <- function(weekday="", month, day, year=2012) {
  # put in the header and a bookmark
  paste("### ", 
        paste('<a name="',makeDayLinkName(month,day,year),'">',weekday," ", day," ", month,"</a>",sep=""))
}
todaysNotes <- function(fname,marker="notes") {
  paste("<a href='../Notes/", fname, "'>",marker,"</a>",sep="")
}
```
**Class Schedule**

        | : | M | W | F | : | M | W | F | : | M | W | F | : | M | W | F | : | M | W | F
--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
*Sept* | | | `r I(dd("Sept",5))` | `r I(dd("Sept",7))` | |`r I(dd("Sept",10))` |`r I(dd("Sept",12))` |`r I(dd("Sept",14))` | | `r I(dd("Sept",17))` |`r I(dd("Sept",19))` |`r I(dd("Sept",21))` | | `r I(dd("Sept",24))` |`r I(dd("Sept",26))` |`r I(dd("Sept",28))` | | | | 
*Oct* |  |  `r I(dd("Oct",1))` |  `r I(dd("Oct",3))` | `r I(dd("Oct",5))` | | `r I(dd("Oct",8))` |`r I(dd("Oct",10))` |`r I(dd("Oct",12))` | | `r I(dd("Oct",15))` |`r I(dd("Oct",17))` |`r I(dd("Oct",19))` | | `r I(dd("Oct",22))` |`r I(dd("Oct",24))` | 26 | | `r I(dd("Oct",29))` |`r I(dd("Oct",31))` |
*Nov* | | | | `r I(dd("Nov",2))` | | `r I(dd("Nov",5))` |  `r I(dd("Nov",7))` | `r I(dd("Nov",9))` | |  `r I(dd("Nov",12))` | `r I(dd("Nov",14))` | `r I(dd("Nov",16))` | | `r I(dd("Nov",19))` | `r I(dd("Nov",21))` | 23 | |  `r I(dd("Nov",26))` | `r I(dd("Nov",28))` | `r I(dd("Nov",30))` 
*Dec* | | `r I(dd("Dec",3))` | `r I(dd("Dec",5))` | `r I(dd("Dec",7))` | | `r I(dd("Dec",10))` 

`r I(classDayContents("Wed", "Sept", 5 ))`
**Topic**: Introduction to the course. Randomness, modeling, and inference.
**Reading**: Statistical Modeling §1.1, 1.2, 1.3
**Assignment**: 
* Do the reading! 
* AcroScore set up
* Pre-course survey

**In-class**: Starting with R. (Write a description of this activity)
Notes`r I(todaysNotes("2012-09-05.html", ":"))`

`r I(classDayContents("Fri", "Sept", 7 )) # ==============================`
**Topic**: Data: cases, variables, tables, and codebooks
**Reading**: Statistical Modeling §1.4, §2.1, 2.2, 2.3, 2.4
**Assignment**:

`r I(classDayContents("Mon", "Sept", 10 ))`
**Topic**: Descriptive statistics
**Reading**: SM §2.5, SM §3.1, 3.2, 3.3
**Assignment**:
* Elevator experiment

`r I(classDayContents("Wed", "Sept", 12 ))`
**Topic**: Descriptive statistics: variance
**Reading**: SM §3.4, 3.5
**Assignment**:

`r I(classDayContents("Fri", "Sept", 14 ))`
**Topic**: Groupwise Models
**Reading**: SM Ch. 4
**Assignment**:
**In Class**:
* Weekly Quiz

`r I(classDayContents("Mon", "Sept", 17 ))`
**Topic**: Model values, residuals, and variance.  Sampling and resampling.
**Reading**: SM Ch. 4 (review).  SM §5.1, 5.2
**Assignment**:

`r I(classDayContents("Wed", "Sept", 19 ))`
**Topic**: Confidence intervals
**Reading**: SM §5.3, 5.4, 5.5, 5.7
**Assignment**:
**In Class**:
* 

`r I(classDayContents("Fri", "Sept", 21 ))`
**Topic**: Language of Models
**Reading**: SM §6.1, 6.2, 6.3, 6.4
**Assignment**:
**In Class**:
* Quiz on R

`r I(classDayContents("Mon", "Sept", 24 ))`
**Topic**: From Model Terms to Formulas and Coefficients
**Reading**: SM §6.5, 6.6, SM §7.1, 7.2
**Assignment**:

`r I(classDayContents("Wed", "Sept", 26 ))`
**Topic**: Formulas and Coefficients
**Reading**: SM §7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9
**Assignment**:

`r I(classDayContents("Fri", "Sept", 28 ))`
**Topic**: Fitting and Least Squares
**Reading**: SM §7.10, SM §8.1, 8.2 
**Assignment**:

`r I(classDayContents("Mon", "Oct", 1 ))`
**Topic**: Geometry of Least Squares Fitting
**Reading**: SM §8.3
**Assignment**:

`r I(classDayContents("Wed", "Oct", 3 ))`
**Topic**: Redundancy and Colinearity
**Reading**: SM §8.4, 8.5
**Assignment**:

`r I(classDayContents("Fri", "Oct", 5 ))`
**Topic**: Correlation and Partitioning, $R^2$
**Reading**: SM Ch. 9
**Assignment**:

`r I(classDayContents("Mon", "Oct", 8 ))`
**Topic**: Correlation and Partitioning (continued)
**Reading**: SM Ch. 9 (review)
**Assignment**:

`r I(classDayContents("Wed", "Oct", 10 ))`
**Topic**: Total and Partial Relationships
**Reading**: SM Ch. 10
**Assignment**:

`r I(classDayContents("Fri", "Oct", 12 ))`
**Topic**: Total and Partial Relationships (continued)
**Reading**: SM Ch. 10 (review)
**Assignment**:

`r I(classDayContents("Mon", "Oct", 15 ))`
**Topic**: Confidence Intervals on Coefficients
**Reading**: SM Ch. 12
**Assignment**:

`r I(classDayContents("Wed", "Oct", 17 ))`
**Topic**: Review for Exam
**Reading**:
**Assignment**:

`r I(classDayContents("Fri", "Oct", 19 ))`
**Topic**: 
**Reading**:
**Assignment**:
**In class**:
* Mid-term Exam

`r I(classDayContents("Mon", "Oct", 22 ))`
**Topic**: Confidence Intervals on Coefficients (continued)
**Reading**: SM Ch. 12
**Assignment**:

`r I(classDayContents("Wed", "Oct", 24 ))`
**Topic**: Probability Models
**Reading**: SM Ch. 11
**Assignment**:

`r I(classDayContents("Fri", "Oct", 26 ))`
*FALL BREAK*

`r I(classDayContents("Mon", "Oct", 29 ))`
**Topic**: Hypothesis Testing
**Reading**: SM Ch. 13
**Assignment**:

`r I(classDayContents("Wed", "Oct", 31 ))`
**Topic**: Hypothesis Testing
**Reading**: SM Ch. 13 (review)
**Assignment**:

`r I(classDayContents("Fri", "Nov", 2 ))`
**Topic**: Testing Whole Models with $latex R^2$ and F
**Reading**: SM §14.1, 14.2, 14.3, 14.5
**Assignment**:

`r I(classDayContents("Mon", "Nov", 5 ))`
**Topic**: Interpreting the p-value
**Reading**: 
* SM §14.4
* XKCD cartoon.
**Assignment**:

`r I(classDayContents("Wed", "Nov", 7 ))`
**Topic**: Hypothesis Testing on Parts of Models
**Reading**: SM Ch. 15
**Assignment**:

`r I(classDayContents("Fri", "Nov", 9 ))`
**Topic**: Hypothesis Testing on Parts of Models (continued)
**Reading**: SM Ch. 15 (review)
**Assignment**:

`r I(classDayContents("Mon", "Nov", 12 ))`
**Topic**: Choosing model terms
**Reading**:
**Assignment**:

`r I(classDayContents("Wed", "Nov", 14 ))`
**Topic**: Non parametrics
**Reading**:
**Assignment**:

`r I(classDayContents("Fri", "Nov", 16 ))`
**Topic**: Logistic regression
**Reading**: SM Ch. 16
**Assignment**:

`r I(classDayContents("Mon", "Nov", 19 ))`
**Topic**: Logistic regression
**Reading**: SM Ch. 16
**Assignment**:

`r I(classDayContents("Wed", "Nov", 21 ))`
**Topic**: Logistic regression
**Reading**: SM Ch. 16
**Assignment**:

`r I(classDayContents("Fri", "Nov", 23 ))`
*THANKSGIVING BREAK*

`r I(classDayContents("Mon", "Nov", 26 ))`
**Topic**: Causation
**Reading**: SM Ch. 17
**Assignment**:

`r I(classDayContents("Wed", "Nov", 28 ))`
**Topic**: Causation
**Reading**: SM Ch. 17
**Assignment**:

`r I(classDayContents("Fri", "Nov", 30 ))`
**Topic**: Causation
**Reading**: SM Ch. 17
**Assignment**:

`r I(classDayContents("Mon", "Dec", 3 ))`
**Topic**: Experiment and Design
**Reading**: SM Ch. 18
**Assignment**:

`r I(classDayContents("Wed", "Dec", 5 ))`
**Topic**: Experiment and Design
**Reading**: SM Ch. 18
**Assignment**:

`r I(classDayContents("Fri", "Dec", 7 ))`
**Topic**: Experiment and Design
**Reading**: SM Ch. 18
**Assignment**:

`r I(classDayContents("Mon", "Dec", 10 ))`
**Topic**: Course Review and Wrap-Up
**Reading**:
**Assignment**:
