Stats 155 Class Notes 2012-10-10
================================

```{r name="setup", child="notes-setup.Rmd"}
# boilerplate
```





Review
=======
$R^2$ between zero and 1.  
* Use delta with nested models to decide if a model is better than junk.
* SAT versus GPA, $R^2 \approx 0.16$.  Based on thousands of student records.
* Little $r$ and the meaning of $r=0.40$

Question about grades: How would you decide if the SAT is deficient or whether it is as good as it can possibly be and grades are deficient?

Survey Project
===============

1. Hand out [project description](http://dl.dropbox.com/u/5098197/Exercises/HTML/ISM-ISM-Spring-2011-Term-Project/ISM-ISM-Spring-2011-Term-Project-A.html?access=ISM3) They are going to be creating a Google Form to collect the data.
2. Ask for suggestions about project areas
3. Have students form groups around common interests. 


Partial versus total
===============

### Review of Partial Derivatives

Change of one variable holding the other ones constant

* Calculation from a model formula using coefficients
* Calculation from model function by evaluating at nearby points

### Real-world examples

* Insurance example: Should we pay people not to be on the College's health plan?
* NGOs and development aid: Speaker Christie Hansen talked about how donors for health funding in Kenya ended up funding other activities as the government moved money away from health toward agriculture, etc.
* Merit aid. Will it reduce net tuition or increase it. Depends on whether we substantially change the yield.

### Activity

[Total-vs-partial In-class activity](https://dl.dropbox.com/u/5098197/ISM/total-partial.pdf)

Car data: work with the two-dimensional graphs