Stats 155 Class Notes 2012-10-03
================================

```{r name="setup", child="notes-setup.Rmd"}
# boilerplate
```

Main Ideas for Today
====================

1. From Model Terms to Vectors
    1. The intercept term as a vector of 1s
    1. Understanding interaction terms as vectors
1. The geometry of fitting against two vectors.
1. Colinearity and why adding model terms changes the coefficients on old terms.  (Reference: housing prices versus bedrooms with and without  living area)
    1. Simpson's paradox, geometrically.
    1. Extreme colinearity: redundancy

Heads up for the future: colinearity has an important effect on confidence intervals.

Review of Geometry through Arithmetic
===================

* scaling
* addition
* linear combination
* square-length is sum of squares
* dot product operation `sum(a*b)`
* angle in terms of a dot product
* projection as a dot product
* orthgonality is when the dot product is zero.

From Model Terms to Vectors
====================

Derive the model vectors for interaction terms.

Fitting with Multiple Vectors
===================

### 1. Diagram with two explanatory vectors

### 2. Show that the residual is orthogonal to each and every model vector.

