Epidemiology Notes 2012-10-09
=====================

When to screen *Contagion*?

In the News
=============
* [Record linking news](http://www.nytimes.com/2012/10/09/us/social-security-death-record-limits-hinder-researchers.html?hp)
* [Meningitis outbreak](http://www.nytimes.com/2012/10/09/health/cdc-says-thousands-exposed-to-steroid-linked-to-meningitis.html)
    * What's the attack rate?
    * What's the case fatality rate?
    * What's the case definition?
    * How come such a small, rare outbreak can be detected and traced back to its cause while "The Cancer-Cluster Myth" claims that common clusters of cancer don't provide evidence for a local cause for cancer?

Quiz
=============
[Reading quiz](Activities/quiz-2012-10-09.pdf)

Population Attributable Fraction
=============
Finally!?!

### Reading from "On Washing Hands"

* [Lister's second article in the Lancet](http://www.bartleby.com/38/6/1.html)

page 21. 
> "We always hope for the easy fix: the one simple change that will erase a problem in a stroke.  But few things in life work this way.  Instead, success requires making a hundred small steps go right --- one after the other, no slipups, no goofs, everyone pitching in.  We are used to thinking of doctoring as a solitary, intellectual task.  But making medicine go right is less often like making a difficult diagnosis than like making sure everyone washes their hands."

### Eradication of disease

What are the differences between polio and smallpox.

General problems that prevent eradication

* reservoir outside humans (yellow fever in mosquito eggs)
* transmissible, subclinical infections ([yaws](http://en.wikipedia.org/wiki/Yaws) and polio)
* false positives (polio --- not all paralysis is polio)
* survivability outside body (60 days for polio virus)
* resistence to vaccination (e.g. rumors about infertility, autism, "getting fevers")

What about polio made it potentially feasible to eradicate:
* oral vaccine that is itself infectious

In "Mopping Up"

* Why do they need 90% vaccination?  (See the [basic reproduction number](http://en.wikipedia.org/wiki/Basic_reproduction_number) for polio: 5-7.)

### SIR Model

Three groups: Susceptible, Infected, Recovered

$\frac{dS}{dt} = - \beta S I$
<br />
$\frac{dI}{dt} = \beta S I - \gamma I$
<br />
$\frac{dR}{dt} = \gamma I$

Use the `mSIR( )` manipulate applet in R, install with `fetchData("mSIR.R"")`

#### The Tipping Point

Prob. of infection: 0.1
Contacts per Day: 9
Duration of disease decay: .799
Initial infected: 1

About 20% of the population gets the disease.

Explore some policy implications:

* Change contacts per day --- big effect
* Change probability of infection --- big effect
* Number of initial infected --- little effect

What happens as duration is increased?  (NOTE: This means lowering the parameter.  You can see this by setting probability of infection to 0 and the initial infected to 50 --- then the exponential decay of infected shows up directly. 

#### Endemic Disease

Prob. of Infection: 0.35
Contacts per day: 5
Duration of disease decay: 0.457
Initial infected: 5
Births/day: 20


Eradication of Polio
----------------

* Eradication and immunization.  Herd immunity.  Why was smallpox successful but polio not so much.
* Highly visible signs makes it easy to diagnose.
* Short time scale prevents people from travelling far.
* Sickness makes it difficult to travel.  It's easy to avoid sick people.
* Spread almost entirely by contact: no fomites (or very few).  In contrast, polio can survive for a long time outside the body.



Hans Rossling Video on the spread of HIV
----------------
[Link to video](http://www.ted.com/talks/hans_rosling_the_truth_about_hiv.html)

Treatment is too costly, must stop transmission.

Is it war?  Zambia is peaceful but has a high rate.
Is it poverty? More money, more HIV at the macro level.  Look at Tanzania in income groups

Multiple partners
less condom use
age-disparate sex

Concurancy
Virus types m

Risk of infection in 1 intercourse: 1:1000 for healthy, 1:100 for unhealthy
Sweden: Serial monogamy therefore clamydia (which sticks around for many years)

HIV has a peak of 3-6 weeks.



* What did he have to say about $\beta$?
* What about $c$?
* What about $D$?  Botswana, people can survive 10-20 years.  Affects the prevalence but also the transmission.