Epidemiology Notes 2012-11-06
=====================
```{r message=FALSE,error=FALSE,warning=FALSE,echo=FALSE,results="hide"}
require(mosaic, quietly=TRUE)
```


### Outline for the Day
Handouts: page 600 of organic food and health article --- to let students identify covariates.
1. Covariates: 
    * Atlantic Flu Vaccine
    * Organic food and health.  Identifying covariates.  Adjusting for them.  Meaning of p-value
2. Causation: 
    * Quick review of Austin Bradford Hill criteria
    * Rhetorical style of "Myopia and ambient lighting" --- read through the article showing how the Hill criteria appear.

### Atlantic Flu Vaccine

> "Study after study has found that people who get a flu shot in the fall are about half as likely to die that winter -- from any cause -- as people who do not."

> "Influenza causes only a small minority of all deaths in the U.S., even among senior citizens, and even after adding in the deaths to which flu might have contributed indirectly. When researchers from the National Institute of Allergy and Infectious Diseases included all deaths from illnesses that flu aggravates, like lung disease or chronic heart failure, they found that flu accounts for, at most 10 percent of winter deaths among the elderly. So how could flu vaccine possibly reduce total deaths by half?"

> "Nobody really has a handle on how many of the deaths that are blamed on flu were actually caused by a flu virus, because few are confirmed by a laboratory. "I used to be a family physician," says Jefferson. "I've never seen a patient come to my office with H1N1 written on his forehead. When an old person dies of respiratory failure after an influenza-like illness, they nearly always get coded as influenza."

> p. 50.  Other way flu researchers are fooled into thinking the vaccine is effective: use of a surrogate endpoint.  Need for placebo-controlled studies.

### Consumption of Organic Foods and Risk of Atopic Disease

[Title page](http://dl.dropbox.com/u/5098197/Epidemiology/Figures/file14519-title.png)

* Display covariate table on p. 3 (print this out for class) and ask them to look for possible covariates
    * Breast feeding
    * Immunization
    * Exposure to smoke
    * Antibiotic exposure in first 6 months
    * "Although a trend for an association between organic food consumption and lower eczema risk was observed, this did not reach statistical signiﬁcance (Table 2). The adjusted OR were 0·95 (95 % CI 0·70, 1·28) and 0·76 (95 % CI 0·50,1·17) for moderately organic food consumption and strict organic food consumption compared to conventional food consumption."
    *[Table 2](http://dl.dropbox.com/u/5098197/Epidemiology/Figures/file14519-table2.png): Adjusted odds ratio.  By and large, adjustment pushes the OR toward 1.
    * [Table 3](http://dl.dropbox.com/u/5098197/Epidemiology/Figures/file14519-table3.png Table 3): Break-down into food categories.  Note that there is no Bonferonni adjustment.  Five food categories suggests that there is no significant result.

### [Epiville Cohort Studies](http://epiville.ccnmtl.columbia.edu/cohort_study/)

* Question 3: Notice that the eligibility criteria exclude people who are already sick.  (It might be that sick people are more likely to work in the dangerous areas of the plant: "What have I got to lose?  Nobody else will hire me."

* "Intellectually Curious" following question 6.  Note the dose-dependence.


Risk
==========

